selenium_node node['selenium']['node']['servicename'] do
  host node['selenium']['node']['host']
  port node['selenium']['node']['port']
  jvm_args node['selenium']['node']['jvm_args']
  proxy node['selenium']['node']['proxy']
  maxSession node['selenium']['node']['maxSession']
  register node['selenium']['node']['register']
  registerCycle node['selenium']['node']['registerCycle']
  hub node['selenium']['node']['hub']
  capabilities node['selenium']['node']['capabilities']
  servlets node['selenium']['hub']['servlets']
  withoutServlets node['selenium']['hub']['withoutServlets']
  nodeStatusCheckTimeout node['selenium']['hub']['nodeStatusCheckTimeout']
  nodePolling node['selenium']['hub']['nodePolling']
  unregisterIfStillDownAfter node['selenium']['hub']['unregisterIfStillDownAfter']
  downPollingLimit node['selenium']['hub']['downPollingLimit']
  debug node['selenium']['hub']['debug']
  timeout node['selenium']['hub']['timeout']
  browserTimeout node['selenium']['hub']['browserTimeout']
  jettyMaxThreads node['selenium']['hub']['jettyMaxThreads']
  log node['selenium']['hub']['log']
  username node['selenium']['node']['username']
  password node['selenium']['node']['password']
  action :install
end
