---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]
      - ["forwarded_port", {guest: 5555, host: 5555}]

suites:
  - name: selenium_test
    run_list:
      - recipe[selenium_test::package]
      - recipe[selenium_test::java]
      - recipe[selenium_test::hub]
      - recipe[selenium_test::node]
      - recipe[selenium_test::htmlunit]
      - recipe[selenium_test::phantomjs]
      - recipe[selenium_test::phantomjs_nogrid]
    attributes:
      java:
        jdk_version: '7'
