default['selenium']['node']['service_name'] = 'selenium_node' # used by node recipe only
default['selenium']['node']['host'] = 'ip'
default['selenium']['node']['port'] = 5555
default['selenium']['node']['jvm_args'] = nil
default['selenium']['node']['proxy'] = 'org.openqa.grid.selenium.proxy.DefaultRemoteProxy'
default['selenium']['node']['maxSession'] = 5
default['selenium']['node']['register'] = true
default['selenium']['node']['registerCycle'] = 5000
default['selenium']['node']['hubPort'] = 4444
default['selenium']['node']['hubHost'] = 'ip'
default['selenium']['node']['capabilities'] = []
default['selenium']['node']['additional_args'] = []
default['selenium']['node']['display'] = ':0'
default['selenium']['node']['username'] = nil
default['selenium']['node']['password'] = nil
default['selenium']['node']['domain'] = nil
